FROM python:3.12

LABEL fr.asso.ort.lyon.authors="3OLEN - Lumos Camminus"

HEALTHCHECK CMD ["python", "--version"]

WORKDIR /usr/src/scripts

# Define user to prevent root-user
RUN adduser --allow-bad-names --disabled-password cli \
    && chown -R cli /usr/src/scripts

USER cli

CMD ["python"]
