theme: minima
title: 3OLEN - Cours
description: Ensemble des ressources pour les cours complémentaires des 3OLEN.
timezone: Europe/Paris

collections:
  courses:
    output: true
  tutorials:
    output: true

defaults:
  - scope:
      type: courses
    values:
      layout: course
  - scope:
      type: tutorials
    values:
      layout: tutorials/page
  - scope:
      path: "_tutorials/*/00.md"
    values:
      layout: tutorials/index
